// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEmpleadosAPI.Datos;

#nullable disable

namespace ProyectoEmpleadosAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819205459_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oficina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpleado")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Empleados", (string)null);

                    b.HasDiscriminator<string>("TipoEmpleado").HasValue("Empleado");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.PersonalExterno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmpresaExterna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPersonal")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.ToTable("PersonalExterno", (string)null);

                    b.HasDiscriminator<string>("TipoPersonal").HasValue("PersonalExterno");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.Cajero", b =>
                {
                    b.HasBaseType("ProyectoEmpleadosAPI.Modelos.Empleado");

                    b.Property<bool>("ManejaEfectivo")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroCaja")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PuedeHacerDepositos")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedePagarCheques")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Cajero");
                });

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.GerenteAgencia", b =>
                {
                    b.HasBaseType("ProyectoEmpleadosAPI.Modelos.Empleado");

                    b.Property<bool>("AccesoADatosSensibles")
                        .HasColumnType("bit");

                    b.Property<string>("AgenciaAsignada")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroEmpleadosACargo")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Gerente");
                });

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.GestorCreditos", b =>
                {
                    b.HasBaseType("ProyectoEmpleadosAPI.Modelos.Empleado");

                    b.Property<decimal>("LimiteCreditoAutorizable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumeroClientesAsignados")
                        .HasColumnType("int");

                    b.Property<bool>("PuedeAbrirCuentas")
                        .HasColumnType("bit");

                    b.Property<bool>("PuedeVenderSeguros")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Gestor");
                });

            modelBuilder.Entity("ProyectoEmpleadosAPI.Modelos.Conserje", b =>
                {
                    b.HasBaseType("ProyectoEmpleadosAPI.Modelos.PersonalExterno");

                    b.Property<string>("DepartamentoAsignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turno")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Conserje");
                });
#pragma warning restore 612, 618
        }
    }
}
